### ISSUE TITLE
更友好的调试方式思考

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs-debug#1]
目前 

``` js
seajs.config({
  debug: true
})
```

上面的 debug 状态只起到两个作用：
1. `seajs.log` 信息会输出
2. 插入的 script 元素会保留，不会自动删除

通过 url 上添加 `?seajs-debug` 的方式，则会自动加载 seajs-debug 插件。

目前 plugin-debug 插件需要通过配置本地 http 可访问的 sea-config.js 来完成各种功能，比如
- 解 combo（这个目前通过 combo 插件的配置来完成）
- 将压缩版本映射到 debug 版本

这一块使用成本偏高，很多同事还不知道可以这么用，知道这么用的，也略嫌麻烦而不怎么使用。

如何让调试更方便，还需要仔细考量下。欢迎各种建议。

**Comment by lifesinger** [comment]
debug 插件的核心功能，是给用户提供一个加载自定义 config 的可扩展点，目前所有自定义 config 信息，都需要存在一个本地文件里，并且需要 http server 来访问。

一个优化点是，利用本地存储，不再依赖 http server，直接弹出一个可编辑框让用户编辑即可。

做到这一步就好。

**Comment by yolio2003** [comment]
针对“nocache 插件去掉了，用得不多，自己清缓存，或在 debug 插件中加 map 就行。”表示
其实最关心nocache啥时候可以用了,否则无法根本无法使用2.1.0，加map不会用求文档教程
