### ISSUE TITLE
是否提供对线上代码直接编辑的功能或其他更好的方式

### ISSUE THREAD

**Issue by lizzie** [seajs/seajs-debug#11]
偏右提到的:

> 类似于 https://github.com/wsvn53/fedit 中可以直接在 fiddle 中编辑某个 js 载入后的脚本, 存储到本地某个临时文件, 然后载入时直接映射到这个临时文件.

存在的问题:
- 不支持 file:// 协议, 即 js 没法读取本地文件, HTML5 中有文件接口, 但要设置权限.
- 读取不行, 同样存临时文件就更不行了.
- 在网页上编辑代码, 还不如在本地编辑器里编辑, 有高亮等各种人性化功能 (from 冒顿)

其他的方式:

我想到以前 云谦做的 idebug, 部署一个公共服务, 抓取 线上代码填入 textarea, 供用户修改后存储到服务器上的临时文件, 生成个临时地址隐射过来. -- 这个还算是可行的

**Comment by lifesinger** [comment]
通过 Chrome 的插件或许可以做到，不过感觉成本好高的。

先把当前版本完善发布后，后续再看用户反馈吧。
