### ISSUE TITLE
nocache没有判断使用?还是&

### ISSUE THREAD

**Issue by Aturan** [seajs/seajs-debug#12]
`http://host/path/to?callback=define`
使用了nocache后是
`http://host/path/to?callback=define?t=1383017904184`
而不是
`http://host/path/to?callback=define&t=1383017904184`

**Comment by lizzie** [comment]
呃... 忘了判断... 马上改回来.

**Comment by lizzie** [comment]
@Aturan 最新仓库 build 出来的 1.1.1 版本的 seajs-debug, 使用上还有些问题, 要等 seajs 2.2.0 出来, 才能正常使用.
