### ISSUE TITLE
seajs-debug无法运行

### ISSUE THREAD

**Issue by weekeight** [seajs/seajs-debug#13]
我把_seajs-debug_这个项目clone到本地，把文件全部放在本地的服务器，然后访问http://localhost/seajs-debug/examples/?seajs-debug，并未出现文档所言的右下角浮框，并有代码提示错误，如下图

![image](https://f.cloud.github.com/assets/1918022/1741908/30323162-63ee-11e3-8efc-0824252c25ac.png)

请问这是为什么呢？我并没有修改任何文件。
此外，[seajs-debug说明文档](https://github.com/seajs/seajs-debug/issues/4)有个地方写多了一个横杆，如下图：

![image](https://f.cloud.github.com/assets/1918022/1741953/4d012ae0-63ef-11e3-93ac-f7740b361bf2.png)

**Comment by lizzie** [comment]
引入 seajs-style 这个插件

**Comment by lizzie** [comment]
文档错误已改正

**Comment by afc163** [comment]
在文档里加一下吧？

或者应该配到 spm.alias 里，作为 seajs 的插件，自己却没有管理依赖，有点尴尬。

**Comment by weekeight** [comment]
@lizzie 可是本来例子里面本身就已经引入这个插件的了哦
![image](https://f.cloud.github.com/assets/1918022/1741963/a500500e-63ef-11e3-92d4-f764d4cb5d15.png)

**Comment by weekeight** [comment]
@lizzie @afc163 上面发的那个截图可以看到包括seajs,seajs-style-debug是一起通过combo合并返回的，还要怎么引入？能否具体说说？

**Comment by lizzie** [comment]
用 seajs-style 1.0.0 这个版本的. seajs-debug 用 1.0.0 

@afc163 ok, 加上

**Comment by lizzie** [comment]
@afc163 但是其他组件也没写明啊... 你看 confirmbox, require(css) 打包后就 seajs.importStyle 了..

**Comment by afc163** [comment]
confirmbox 模块和 seajs 插件不是一个层次。
seajs 插件和 seajs 插件是一个层次的依赖吧。

**Comment by weekeight** [comment]
@lizzie @afc163 恩恩？是怎样呢？看了上面的回复还是不知道怎么解决啊？能否先把项目里面的例子让它能正常跑起来先啊？是版本不兼容的问题吗？那如果我要使用的是seajs@2.1.1的话会有影响么？
