### ISSUE TITLE
当线上JS代码报错时，是否可以禁用seajs-debug？

### ISSUE THREAD

**Issue by mopduan** [seajs/seajs-debug#14]
由于采用了另一种本地调试方式，目前用不上seajs-debug插件，但是一报错就会在chrome的console里看到，是否可以禁用？谢谢！

**Comment by mopduan** [comment]
seajs.config里设置  debug:false 是否可以？

**Comment by popomore** [comment]
不知道你怎么用的，报错和 seajs-debug 没关系。如果你想在报错的时候用 seajs-debug 调试倒是可以，请仔细读文档。
