### ISSUE TITLE
插件生成的debug文件有问题

### ISSUE THREAD

**Issue by nuintun** [seajs/seajs-debug#6]
``` js
loc.search.indexOf("seajs-debug-debug") > -1
```

插件的`debug`文件都生成这样了~

**Comment by lifesinger** [comment]
能详细说下前因后果了？我看不懂上下文-.-

**Comment by yyclaw** [comment]
没错啊

**Comment by nuintun** [comment]
@lifesinger 没事了，thanks~ 我的意思是`seajs-debug-debug.js`造成调试时候`uri`调用方式是`?seajs-debug-debug`，和文档中`?seajs-debug`不一致了，影响不大！

**Comment by lepture** [comment]
@NewtonNiu 谁说的？你还是用 `?seajs-debug` 呀，因为你引入的 `seajs-debug` 文件是那个压缩好的。

**Comment by hotoo** [comment]
@lifesinger 是用 spm 打包的么？如果是的话，那可能是 spm 的问题。

**Comment by lepture** [comment]
@hotoo 请看 Makefile

**Comment by hotoo** [comment]
这是一个特性，但表示不理解。

**Comment by nuintun** [comment]
@lepture Makefile里面的替换应该是想替换``define('seajs-debug')`
