### ISSUE TITLE
新版 seajs-debug 的一些建议

### ISSUE THREAD

**Issue by afc163** [seajs/seajs-debug#7]
想到先写下来备忘。
1. 代码用等宽字体。
2. 扁平化样式风格。
3. 字体和按钮稍稍放大点。
4. 输入框 placeholder。
5. 这里应该是硬编码：https://github.com/seajs/seajs-debug/blob/master/src/seajs-debug.js#L533
6. 下面的按钮作为常用功能，是否应该放在面板中央的醒目位置，而 map 功能相对次要。
7. 显示模块数和 seajs 加载性能。
8. 显示 seajs-health 的相关信息？

**Comment by afc163** [comment]
写到 7 8 点突然想到，seajs 调试插件是不是就应该把 seajs 运行时的一些数据（模块数、加载性能、依赖深度、是否循环依赖）显示在面板的固定区域。所以 seajs-health 是不是应该和 seajs-debug 进行合并，这俩本来都是一个场景下的应该提供的功能。

**Comment by popomore** [comment]
合并的话感觉略大吧，debug 只做调试比较简单吧。

**Comment by afc163** [comment]
都是调试场景，感觉分两个插件没必要，不利于用户认知。

**Comment by popomore** [comment]
health 主要的还是状态展示，不只是为了排错，做的好可能需要很多代码。

**Comment by leoner** [comment]
> 显示 seajs-health 的相关信息？
> 觉得应该支持, 默认可以不显示, 但是可以通过一个按钮啥的, 可以加载进来呀!

**Comment by lizzie** [comment]
同意 @leoner 的, 可以类似加载 seajs-log 那样, 点击一个按钮, 就把 seajs-health 加载进来, 但功能上 debug 和 health 还是分开好.

**Comment by lizzie** [comment]
> 1. 代码用等宽字体。 

采用 `font-family: Courier, monospace;`

> 1. 扁平化样式风格。 

换了个皮肤, 紫色的, @afc163 您瞧瞧看? 

> 1. 字体和按钮稍稍放大点。

文本字体调成 14px , 标题 16px

> 1. 输入框 placeholder。

已加, 不过之前也是有 title 的

> 1. 这里应该是硬编码：https://github.com/seajs/seajs-debug/blob/master/src/seajs-debug.js#L533 

这个是要给出 seajs-log 的 url, 在插件加载方式 [#794](https://github.com/seajs/seajs/issues/794) 中列出的三种方式, 如果换成 url 上加  seajs-log 的话, 也是需要用户指定 alias 告诉 seajs seajs-log 插件在哪, 同 preload 给出 seajs-log 的 url 一样. 没想到其他的方式. **求更好的方式**

> 1. 下面的按钮作为常用功能，是否应该放在面板中央的醒目位置，而 map 功能相对次要。

放中间太丑, 现在 icon 调大到 16px

**Comment by popomore** [comment]
panel 的样式是不是可以打包到 js 里？

输入框还挺好用的，当作简单的 console 了。

**Comment by popomore** [comment]
https://github.com/seajs/seajs-debug/blob/master/src/seajs-debug.js#L75

https://github.com/seajs/seajs-debug/blob/master/src/seajs-debug.js#L80

引其他插件的是不是不该硬编码？

就 preload，然后配 alias 不行？不配的话会 404，也很容易发现。

**Comment by lizzie** [comment]
@popomore 嗯, 我改掉, 换成 preload + alias 的方式. 样式可以打包的, 但是康辉不是想重用 css 吗? 所以我暂时给挪出来了.

**Comment by lizzie** [comment]
这个除了 health 的问题外, 都已修复.
