### ISSUE TITLE
seajs debug 和 seajs health 如何整合

### ISSUE THREAD

**Issue by lizzie** [seajs/seajs-debug#8]

**Comment by lizzie** [comment]
满足两种情况:
- seajs-health 显示内容到 seajs debug panel 中, 需要同时载入 seajs-debug 和 seajs-health
- seajs-health 独立显示, 完全独立的UI, 只载入 seajs-health. 

问题:
- 当 ?seajs-debug&seajs-health 时, 有两个 panel 时? 
- seajs-debug-panel 独立, seajs-health / seajs-debug 共享一个 debug-panel. 但当两个需要一起载入的时候, 如何处理?
- 另外, seajs-debug 和 seajs-health 是独立载入的, 没法保证顺序, UI 如何处理?

**Comment by popomore** [comment]
现在有结论么，我觉得 panel 还是分开吧，debug 是可以隐藏的，health 也可以考虑最小化。然后两个 panel 互相添加入口？

而且一般 health 就是为了看一眼，不会像 debug 那样一直存在。

**Comment by lizzie** [comment]
互相加入口, 也有问题啊. 两个载入是异步的... 顺序没法保证... 我再想想看有没办法

**Comment by popomore** [comment]
两个应该没有依赖吧，debug 开启 health 的时候就是切换开关，比如在链接上再加一个 seajs-health 参数。

**Comment by lizzie** [comment]
看最新的 demo

仅 seajs-debug 时
- http://aralejs.org/validator/examples/test.html?seajs-debug
- 调试面板, 点击 health, 载入 health 插件

仅 seajs-health 时
- http://aralejs.org/validator/examples/test.html?seajs-health
