### ISSUE TITLE
测试用例挂了

### ISSUE THREAD

**Issue by popomore** [seajs/seajs-debug#9]
https://travis-ci.org/seajs/seajs/builds/10327542

**Comment by lifesinger** [comment]
是打包的问题。默认简单通过 Makfile 打包已经不能满足需求。

乔花参考 seajs 项目的 Gruntfile，给 debug 插件单独写一个 Gruntfile 来实现打包。

**Comment by lizzie** [comment]
我现在拆开来, 改成 CMD 模块的组织方式了, 直接 spm build 打包

贯高给的链接看不了啊

**Comment by popomore** [comment]
还是给 seajs 单独搞个工具吧，现在插件 example 和 testcase 都没有，不太完整。

@lizzie 访问不了 travis？

**Comment by lizzie** [comment]
现在通过了
